config-version: 1

server-configuration:
  name: "Prison-A"
  meta-reservation-count: 3
  min-meta-reserved-count: 1
  kick-on-load-failure: true
  freeze-player-on-load: true
  compression-configuration:
    mine-local-meta: true
    user-profile-local-meta: true

claim-queue-configuration:
  enabled: true
  max-in-queue: 10
  enable-change-hook: true
  priority:
    default-weight: 10
    weight-map:
      "queue-weight-15": 15
      "queue-weight-20": 20


redis-configuration:
  host: ""
  port: 6379
  username: ""
  password: ""

redis-sync-configuration:
  network-wait-millisecond: 500

sql-configuration:
  host: "server.alenalex.me"
  port: 3306
  username: "u38_4yXN7IXahp"
  password: "ozz2GFlPRg=jbt=vYB+KkZV8"
  database: "s38_npc-core"
  auto-reconnect: true
  use-ssl: false
  hikari-properties:
    pool-name: "prison-a-pool"
    custom-hikari-properties:
      "cachePrepStmts": "true"
      "prepStmtCacheSize": "250"
      "prepStmtCacheSqlLimit": "2048"
      "useServerPrepStmts": "true"
      "useLocalSessionState": "true"
      "rewriteBatchedStatements": "true"
      "cacheResultSetMetadata": "true"
      "cacheServerConfiguration": "true"
      "elideSetAutoCommits": "true"
      "maintainTimeStats": "true"

resetter-configuration:
  resetter-to-use: Internal
  before-reset-identifier: "spawn-point"
  after-reset-identifier: "upper-mine-corner"
  use-after-reset-hook: true

mine-world-configuration:
  world-name: Minas
  mine-distance: 250
  create-void-world-if-absent: true
  default-location:
    world: MineWorld
    x: 0.0
    y: 0.0
    z: 0.0
    float: 0
    pitch: 0

default-mine-configuration:
  mine-access: "CLOSED"
  mine-vault-balance: "100"
  reset-block-choices:
    - "EMERALD_ORE"
    - "EMERALD_BLOCK"